### ISSUE TITLE
pandas 版本不升级下吗

### ISSUE THREAD

**Issue by towry** [JoinQuant/jqdatasdk#17]
1.0.5 了

**Comment by philsong** [comment]
是的，和我的项目冲突。。。！升级吧！

**Comment by pkgod** [comment]
强烈要求升级，这个会影响其他项目的

**Comment by doncat99** [comment]
thrift数据包赶紧升级到pandas1.1.0啊

**Comment by foolcage** [comment]
可以用这个
https://github.com/zvtvz/jqdatapy

**Comment by darylzz** [comment]
jqdatasdk 1.8.6升级了对pandas 新版本的支持了吗？
